# We use `workflow_run` to securely add a comment to the PR.
# PRs opened by external forks do not have write access to their PR, so can't add comments.
name: CI comment

on:
  workflow_run:
    workflows: ["CI", "CI comment test"]
    types:
      - completed

jobs:
  summary:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Download summaries
        id: download
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          pattern: summary-*
          merge-multiple: true
          path: summaries
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: ls -R

      - name: Merge summaries
        id: summary
        run: |
          echo "message<<EOF" >> $GITHUB_OUTPUT
          for file in summaries/*; do
            echo $(cat $file) >> $GITHUB_OUTPUT
          done
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set PR comment
        if: steps.summary.outputs.message
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests.number }}
          header: ${{ github.event.workflow_run.name }}
          message: ${{ steps.summary.outputs.message }}

      - name: Delete PR comment
        if: ${{ !steps.summary.outputs.message }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests.number }}
          header: ${{ github.event.workflow_run.name }}
          delete: true
