name: CI comment test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Test file
        run: echo "Test file" > test.txt

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: summary-test
          path: test.txt
